/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Fatal-Fury-Dominated-Mind-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80051418u
#define func_80051418 BootEntry  /* alias */
